project:
  type: website
  output-dir: docs
  resources:
   - .nojekyll

website:
  title: ""
  sidebar:
    background: "#012169"
    foreground: "#FFFFFF"
    logo: "images/mccourt.png"
    pinned: true
    align: center
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: course_infrastructure.qmd
        text: Course Technology Tools
      - section: "Materials"
        contents:
          - href: weeks/week-01.qmd
            text: "Week 1: Intro to Course and Tools"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
