
---
title: "PPOL 5203 - Data Science I: Foundations - Fall 2026"
subtitle: "McCourt School for Public Policy, Georgetown University"
---

## Course Description

This first course in the core data science sequence teaches Data Science for Public Policy (DSPP) students how to synthesize disparate, possibly unstructured data in order to draw meaningful insights. Topics covered include the fundamentals of object-oriented programming in Python; literate programming; an introduction to algorithms and data types; data wrangling, visualization, and extraction; an introduction to machine learning methods, and text analysis. In addition, students will be exposed to Git and Github for version control and reproducible research. The objective of the course is to teach students how to incorporate data into their decision-making and analysis. No prior programming experience is assumed or required.

Data Science I is a collective effort among DSPP faculty. For this reason, the materials heavily draw from [Dr. Tiago Ventura's](https://venturatiago.com/) version of the course, with some also drawn from materials created by [Dr. Eric Dunford](http://ericdunford.com/)

## Goals

After completing this course, the students will be able to:

-   General understanding of python's object oriented programming syntax and data structures.

-   Competency using version control (Git/Github).

-   Learn to manipulate and explore data with Pandas and other tools.

-   General understanding of analyzing algorithms and data structures.

-   Learn to extract and process data from structured and unstructured sources.

-   Get some intuition of modeling text data in Python.

-   Learn the basics of machine learning as a modeling approach.

-   Learn how to use Generative AI for multiple applied tasks.

-   Learn basics of using SQL to query databases.

## Instructor

-   Professor: [Dr. Rebecca Johnson](https://rebeccajohnson.io/)
-   Email: [rj545\@georgetown.edu](mailto:rj545@georgetown.edu)
-   Office hours:
    -   Time: Every Wednesday, 1130am - 130pm
    -   Location - either:
      - In person: 125E, Office Number 768
      - Remote: see Calendly link

**Sign up**: on [Calendly](https://calendly.com/rebeccajohnsonmtg/ppol-3500-office-hours)

## Teaching Assistant: TBD

### Course Infra-structure

**Class Website**: A class website ADD LINK  will be used throughout the course and should be checked on a regular basis for lecture materials and required readings.

<!--
**Class Slack Channel**: The class also has a dedicated slack channel. You can join on clicking [here](https://join.slack.com/t/ppol5203-fall2025/shared_invite/zt-3cmg2zqoz-uFHOG_a9tsxBBBm2wCz~zg). The channel serves as an open forum to discuss, collaborate, pose problems/questions, and offer solutions. Students are encouraged to pose any questions they have there as this will provide the professor and TA the means of answering the question so that all can see the response. If you're unfamiliar with, please consult the following start-up tutorial (https://get.slack.help/hc/en-us/articles/218080037-Getting-started-for-new-members). Please follow the [***invite link***](https://join.slack.com/t/ppol5203-fall2025/shared_invite/zt-3cmg2zqoz-uFHOG_a9tsxBBBm2wCz~zg) to be added to the Slack channel.
-->


**Canvas**: A Canvas site (http://canvas.georgetown.edu) will be used throughout the course and should be checked on a regular basis for announcements. All announcements for the assignments and classes will be posted on Canvas; they will not be distributed in class or by e-mail. Support for Canvas is available at (202) 687-4949

NOTE: Students are encouraged to run lecture code on their own machines. If you do not have access to a laptop on which you can install `python3`, please contact the professor and/or TA for assistance. Only `python3` will be used in this course.

<!--
**Datacamp:** As part of this course, you will have access to a DataCamp classroom that you can use to take Datacamp modules for free. Join the classroom [here](https://www.datacamp.com/groups/shared_links/0cd82dc4f5a0c59ebb098f26fb7f36a57274d17b315e0dcf27a023fe189a0161) Datacamp courses can be a useful tool for you to practice the concepts we see in class. Although I will not assign specific courses for you,, you can use Datacamp courses to review the topics we cover in class. The lecture notes will cover in details all our in-class discussions. Datacamp courses will be considered additional material.
-->
