---
title: "Schedule"
editor: visual
---

## Weekly Schedule

| Week    | Topic                                                                             | Date               |
|------------------------|------------------------|------------------------|
| Week 01 | Introduction, Installations, IDEs, Command line                                   | August 27, 2026    |
| Week 02 | Version Control, Workflow and Reproducibility: Or a bit of Git & GitHub           | September 3, 2026  |
| Week 03 | Intro to Python - OOP, Data Types, Control Statements and Functions               | September 10, 2026 |
| Week 04 | Intro to Python II: Scaling up your code - Iteration, Comprehension and Functions | September 17, 2026 |
| Week 05 | From Nested lists to Dataframes: Numpy and Intro to Pandas                        | September 24, 2026 |
| Week 06 | Pandas II: Data Wrangling                                                         | October 1, 2026    |
| Week 07 | Joining, Tidying and Visualizing Data                                             | October 8, 2026    |
| Week 08 | Scraping + APIs                                                                   | October 15, 2026   |
| Week 09 | Statistical Learning                                                              | October 22, 2026   |
| Week 10 | Text as Data I: Discovery and Topics                                              | October 29, 2026   |
| Week 11 | Text as Data II: Supervised Learning                                              | November 5, 2026   |
| Week 12 | Generative AI                                                                     | November 12, 2026  |
| Week 13 | SQL                                                                               | November 19, 2026  |
| Week 14 | Presentations of Final Projects                                                   | December 03, 2026  |
